name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
      - name: Install deps
        run: yarn install
      - name: Eslint check
        run: yarn lint
